apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-file-bronze-delayed
parameters:
  billingType: hourly
  classVersion: "2"
  iopsPerGB: "2"
  sizeRange: '[20-12000]Gi'
  type: Endurance
provisioner: ibm.io/ibmc-file
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

# Storage Class -> Un moyen pour les admins de décrires des "classes" de stockages